PREFIX hto:  <http://purl.obolibrary.org/obo/HTO_>
PREFIX obo:  <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:   <https://w3id.org/hto/data/>

SELECT ?statusLabel (AVG(?value) AS ?meanBitterness) (COUNT(?value) AS ?n)
WHERE {
  ?person hto:0000057 ?status .
  OPTIONAL { ?status rdfs:label ?statusLabel }
  ?event hto:0000050 ?person ; hto:0000063 ?assertion .
  ?assertion hto:0000052 hto:0000114 ; hto:0000053 ?rating .
  ?rating hto:0000070 ?value .
} GROUP BY ?statusLabel ORDER BY DESC(?meanBitterness)
