PREFIX hto:  <http://purl.obolibrary.org/obo/HTO_>
PREFIX obo:  <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:   <https://w3id.org/hto/data/>

SELECT ?term WHERE {
  ?term a ?type .
  FILTER(STRSTARTS(STR(?term), "http://purl.obolibrary.org/obo/HTO_"))
  FILTER NOT EXISTS { ?term rdfs:label ?l }
}
