#!/usr/bin/env python3
"""Build a MIREOT-style import module from the EBI OLS4 API.

Why not `robot extract`: the source ontologies total well over a gigabyte
(ChEBI alone is ~700 MB). We need ~55 terms. Fetching those terms by IRI is
faster, reproducible, and produces a module small enough to read in a diff.
The trade-off is that we import each term with its label and definition but
not its full ancestor chain; HTO asserts its own parents, so nothing is lost
for our axioms. This is documented in the README.
"""
from __future__ import annotations
import csv, json, pathlib, sys, time, urllib.parse, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
TERMS = ROOT / "src" / "external_terms.tsv"
OUT = ROOT / "src" / "imports" / "hto_imports.ttl"
OLS = "https://www.ebi.ac.uk/ols4/api/ontologies/{ont}/terms?iri={iri}"


def iri_for(curie: str) -> str:
    prefix, local = curie.split(":", 1)
    return f"http://purl.obolibrary.org/obo/{prefix}_{local}"


def fetch_term(ontology: str, curie: str) -> dict:
    """Return {'iri','label','definition'} for one external term."""
    iri = iri_for(curie)
    url = OLS.format(ont=ontology, iri=urllib.parse.quote(iri, safe=""))
    req = urllib.request.Request(url, headers={"User-Agent": "HTO-build"})
    for attempt in range(3):
        try:
            data = json.load(urllib.request.urlopen(req, timeout=60))
            break
        except Exception:
            if attempt == 2:
                raise
            time.sleep(2 * (attempt + 1))
    terms = data.get("_embedded", {}).get("terms", [])
    if not terms:
        raise LookupError(f"{curie} not found in {ontology}")
    t = terms[0]
    desc = t.get("description") or []
    return {"iri": iri, "label": t["label"],
            "definition": desc[0] if desc else None}


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def main() -> int:
    rows = list(csv.DictReader(open(TERMS), delimiter="\t"))
    lines = [
        "# Generated by scripts/build_imports.py. Do not edit by hand.",
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix obo: <http://purl.obolibrary.org/obo/> .",
        "",
    ]
    for row in sorted(rows, key=lambda r: r["curie"]):
        t = fetch_term(row["ontology"], row["curie"])
        kind = "owl:ObjectProperty" if row["curie"].startswith("RO:") else "owl:Class"
        block = [f'<{t["iri"]}> a {kind} ;', f'  rdfs:label "{escape(t["label"])}" ;']
        if t["definition"]:
            block.append(f'  obo:IAO_0000115 "{escape(t["definition"])}" ;')
        block[-1] = block[-1].rstrip(" ;") + " ."
        lines.extend(block + [""])
        print(f"  {row['curie']:18s} {t['label']}", file=sys.stderr)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} terms)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
