#!/usr/bin/env python3
"""Report which HTO quality terms have no exact match in PATO.

This is the finding that motivates HTO: PATO, the ontology the OBO community
uses for qualities, defines bitter and none of the other basic tastes.
"""
from __future__ import annotations
import csv, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "pato-gap-report.md"

QUALITIES = ROOT / "src" / "templates" / "qualities.tsv"
PATO_MAP = ROOT / "mappings" / "hto-pato.sssom.tsv"


def read_tsv(path: pathlib.Path) -> list[dict]:
    with open(path) as fh:
        lines = [l for l in fh if not l.startswith("#")]
    return list(csv.DictReader(lines, delimiter="\t"))


def main(out: pathlib.Path = OUT) -> int:
    rows = read_tsv(QUALITIES)[1:]          # drop the ROBOT template-string row
    mapped = {r["subject_id"] for r in read_tsv(PATO_MAP)
              if r["predicate_id"] == "skos:exactMatch"}
    lines = [
        "# Which taste qualities does PATO already have?",
        "",
        "Generated by `scripts/gap_report.py`. PATO is the ontology the OBO community",
        "uses for qualities. Of the taste qualities HTO defines, this many have an exact",
        "PATO equivalent:",
        "",
        "| HTO term | label | exact match in PATO |",
        "|---|---|---|",
    ]
    absent = []
    for r in rows:
        cid, label = r["ID"], r["LABEL"]
        if not cid.startswith("HTO:"):
            continue
        has = cid in mapped
        lines.append(f"| `{cid}` | {label} | {'yes' if has else '**no**'} |")
        if not has:
            absent.append(label)
    lines += [
        "",
        f"**{len(absent)} of {len(rows)} HTO quality terms have no PATO equivalent.**",
        "",
        "The four basic tastes among them (sweetness, sourness, saltiness, umami) are",
        "submitted to PATO as new-term requests; see `docs/term-requests/`.",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(absent)} unmatched of {len(rows)}")
    return 0


if __name__ == "__main__":
    # An optional argument names somewhere else to write, so a test can check
    # the report without rewriting the committed one.
    raise SystemExit(main(pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else OUT))
