#!/usr/bin/env python3
"""Render src/templates/interactions.tsv as a readable table in docs/interactions.md.

The interaction rules are the ontology's contribution; requiring SPARQL to read
them would hide them from everyone who is not already an ontologist.
"""
from __future__ import annotations
import csv, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TSV = ROOT / "src" / "templates" / "interactions.tsv"
OUT = ROOT / "docs" / "interactions.md"

LABELS = {}  # CURIE -> label, filled from the quality and vocabulary templates


def load_labels() -> None:
    for name in ("qualities.tsv", "profiles.tsv"):
        path = ROOT / "src" / "templates" / name
        if not path.exists():
            continue
        with open(path) as fh:
            for row in list(csv.DictReader(fh, delimiter="\t"))[1:]:
                LABELS[row["ID"]] = row["LABEL"]
    load_import_labels()


def load_import_labels() -> None:
    """The compounds in demonstrated_with are ChEBI terms, so their labels live
    in the import module rather than in any template. Printing bare CURIEs in
    the column whose entire purpose is to say which stimuli were tested would
    defeat the point of generating this page at all."""
    path = ROOT / "src" / "imports" / "hto_imports.ttl"
    if not path.exists():
        return
    import rdflib
    from rdflib.namespace import RDFS

    graph = rdflib.Graph()
    graph.parse(path, format="turtle")
    for subject, label in graph.subject_objects(RDFS.label):
        local = str(subject).replace("http://purl.obolibrary.org/obo/", "")
        if "_" not in local:
            continue
        prefix, identifier = local.split("_", 1)
        LABELS.setdefault(f"{prefix}:{identifier}", str(label))


def main() -> int:
    load_labels()
    with open(TSV) as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))[1:]
    lines = [
        "# Taste interactions",
        "",
        "Generated by `scripts/interactions_md.py` from `src/templates/interactions.tsv`.",
        "Every rule is directional and names the compounds it was demonstrated with.",
        "Each citation's abstract was read while the rule was written, and the condition",
        "text reports what that abstract actually says. `make verify-citations` is a",
        "separate and weaker check: it resolves each identifier against PubMed, which",
        "confirms the paper exists and its title is plausible but not that it supports",
        "the rule -- as the script's own closing line puts it, resolution is necessary,",
        "not sufficient.",
        "",
        "| Rule | Agent | Effect | Target | Demonstrated with | Condition | Citation |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        effect = "suppresses" if row["effect"] == "HTO:0000231" else "enhances"
        compounds = ", ".join(LABELS.get(c, c) for c in row["demonstrated_with"].split("|"))
        lines.append(
            f"| `{row['ID']}` | {LABELS.get(row['agent'], row['agent'])} | {effect} "
            f"| {LABELS.get(row['target'], row['target'])} | {compounds} "
            f"| {row['condition']} | {row['citation']} |"
        )
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {len(rows)} rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
